In [23]:
import pandas as pd

pd.set_option('display.max_rows', 500)

In [24]:
SELECTED_VARIABLES = [
    "PML-RARA",
    "CBFB-MYH11",
    "monosomy5_del_5q",
    "NPM1",
    "STAG2",
    "KIT",
    "IDH_mutations",
    "IDH2",
    "RUNX1-RUNX1T1_OR_t_8_21",
    "NPM1_OR_FLT3_ITD",
    "TP53",
    "complex_karyotype",
    "monosomal_karyotype",
    "RTK_RAS_mutations",
    "CpG_mutations",
    "FLT3_mutations",
]

SAVE_FILES = True
DATE = "07-04-2026"

MUTATION_INPUT_FILEPATH = "data/sweden/KI_mutations.csv"
BM_VARIABLE_TABLE_PATH = f"data/{DATE}/aml_mut_pred_sample_ids_bm_{DATE}.xlsx"

### **Mutation labels**

In [25]:
df = pd.read_csv(MUTATION_INPUT_FILEPATH)

print(f"Number of available samples: {len(df)}")

# get existing mutation variables in Sweden-KI dataset
existing_variables = [variable for variable in SELECTED_VARIABLES if variable in df.columns]

mutation_labels = df[["album_id", "mgg_database"] + existing_variables]
mutation_labels = mutation_labels.rename(columns={"mgg_database": "database_id"})
mutation_labels[existing_variables] = mutation_labels[existing_variables].replace({True: 1, False: 0})


# filter out samples that have been used in model training
df = pd.read_excel(BM_VARIABLE_TABLE_PATH)
mutation_labels = mutation_labels[
    ~mutation_labels.set_index(["album_id", "database_id"]).index.isin(
        df.set_index(["album_id", "database_id"]).index
    )
]
print(f"Found {len(mutation_labels)} BM samples not in model training")

# create dummy subject_id columns
mutation_labels["subject_id"] = mutation_labels.index

display(mutation_labels)

#if SAVE_FILES:
#    mutation_labels.to_excel(f"data/{DATE}/sweden_mutation_labels_{DATE}.xlsx")

Number of available samples: 87
Found 87 BM samples not in model training

    album_id database_id  NPM1  STAG2  KIT  IDH2  TP53  subject_id
0        693    Venex_KI   0.0    0.0  0.0   1.0   0.0           0
1        763    Venex_KI   0.0    0.0  0.0   0.0   0.0           1
2        762    Venex_KI   1.0    0.0  0.0   0.0   0.0           2
3        793    Venex_KI   0.0    0.0  0.0   0.0   0.0           3
4        690    Venex_KI   0.0    0.0  0.0   0.0   0.0           4
5        759    Venex_KI   0.0    0.0  0.0   1.0   0.0           5
6        688    Venex_KI   0.0    0.0  0.0   0.0   0.0           6
7        656    Venex_KI   0.0    0.0  0.0   0.0   0.0           7
8        687    Venex_KI   0.0    0.0  0.0   0.0   1.0           8
9        750    Venex_KI   1.0    0.0  0.0   1.0   0.0           9
10       792    Venex_KI   1.0    0.0  0.0   0.0   0.0          10
11       749    Venex_KI   0.0    0.0  0.0   0.0   0.0          11
12       764    Venex_KI   0.0    0.0  0.0   0.0   0.0          12
13       683    Venex_KI   1.0    0.0  0.0   0.0   0.0          13
14       682    Venex_KI   0.0    0.0  0.0   1.0   0.0          14
15       681    Venex_KI   1.0    0.0  0.0   0.0   0.0          15
16       679    Venex_KI   0.0    0.0  0.0   0.0   0.0          16
17       678    Venex_KI   0.0    0.0  0.0   0.0   0.0          17
18       677    Venex_KI   0.0    0.0  0.0   0.0   0.0          18
19       695    Venex_KI   0.0    0.0  0.0   0.0   0.0          19
20       791    Venex_KI   0.0    0.0  0.0   0.0   NaN          20
21       674    Venex_KI   0.0    0.0  0.0   1.0   0.0          21
22       673    Venex_KI   0.0    1.0  0.0   1.0   0.0          22
23       787    Venex_KI   0.0    0.0  0.0   0.0   0.0          23
24       786    Venex_KI   1.0    0.0  0.0   0.0   0.0          24
25       784    Venex_KI   0.0    0.0  0.0   0.0   1.0          25
26       783    Venex_KI   1.0    0.0  0.0   0.0   0.0          26
27       782    Venex_KI   0.0    0.0  0.0   0.0   1.0          27
28       735    Venex_KI   0.0    0.0  0.0   1.0   0.0          28
29       806    Venex_KI   0.0    0.0  0.0   0.0   0.0          29
30       807    Venex_KI   0.0    0.0  0.0   0.0   0.0          30
31       805    Venex_KI   1.0    0.0  0.0   0.0   0.0          31
32       731    Venex_KI   0.0    0.0  0.0   0.0   0.0          32
33       729    Venex_KI   0.0    0.0  0.0   1.0   0.0          33
34       730    Venex_KI   0.0    0.0  0.0   0.0   1.0          34
35       802    Venex_KI   1.0    0.0  0.0   0.0   0.0          35
36       727    Venex_KI   0.0    0.0  0.0   0.0   1.0          36
37       726    Venex_KI   0.0    0.0  0.0   1.0   0.0          37
38       772    Venex_KI   0.0    0.0  0.0   1.0   1.0          38
39       724    Venex_KI   0.0    0.0  0.0   0.0   0.0          39
40       820    Venex_KI   0.0    0.0  0.0   0.0   0.0          40
41       722    Venex_KI   1.0    0.0  0.0   0.0   0.0          41
42       776    Venex_KI   0.0    0.0  0.0   0.0   0.0          42
43       652    Venex_KI   0.0    0.0  0.0   0.0   0.0          43
44       777    Venex_KI   0.0    0.0  0.0   0.0   0.0          44
45       719    Venex_KI   0.0    0.0  0.0   0.0   0.0          45
46       718    Venex_KI   0.0    0.0  0.0   1.0   0.0          46
47       717    Venex_KI   0.0    1.0  0.0   1.0   0.0          47
48       716    Venex_KI   0.0    0.0  1.0   0.0   0.0          48
49       651    Venex_KI   1.0    0.0  0.0   0.0   0.0          49
50       650    Venex_KI   0.0    0.0  0.0   0.0   0.0          50
51       817    Venex_KI   0.0    0.0  0.0   0.0   1.0          51
52       822    Venex_KI   1.0    0.0  0.0   0.0   0.0          52
53       816    Venex_KI   0.0    0.0  0.0   1.0   0.0          53
54       712    Venex_KI   0.0    0.0  0.0   0.0   1.0          54
55       825    Venex_KI   0.0    1.0  0.0   0.0   0.0          55
56       826    Venex_KI   0.0    0.0  0.0   0.0   0.0          56
57       709    Venex_KI   1.0    0.0  0.0   0.0   0.0          57
58       739    Venex_KI   0.0    0.0  0.0   0.0   1.0          58
59       707    Venex_KI   0.0    1.0  0.0   0.0   0.0          59
60       830    Venex_KI   1.0    0.0  0.0   0.0   0.0          60
61       831    Venex_KI   0.0    0.0  0.0   1.0   0.0          61
62       832    Venex_KI   1.0    0.0  0.0   0.0   0.0          62
63       814    Venex_KI   0.0    0.0  0.0   0.0   0.0          63
64       833    Venex_KI   0.0    1.0  0.0   1.0   0.0          64
65       834    Venex_KI   0.0    0.0  0.0   0.0   1.0          65
66       813    Venex_KI   0.0    0.0  0.0   1.0   0.0          66
67       835    Venex_KI   1.0    0.0  0.0   1.0   1.0          67
68       700    Venex_KI   0.0    1.0  0.0   0.0   0.0          68
69       698    Venex_KI   1.0    0.0  0.0   0.0   0.0          69
70       697    Venex_KI   0.0    0.0  0.0   0.0   1.0          70
71       800    Venex_KI   0.0    0.0  0.0   0.0   0.0          71
72       644    Venex_KI   1.0    0.0  0.0   0.0   0.0          72
73       696    Venex_KI   0.0    0.0  0.0   0.0   0.0          73
74       640    Venex_KI   0.0    0.0  0.0   0.0   0.0          74
75       811    Venex_KI   0.0    0.0  0.0   1.0   0.0          75
76       812    Venex_KI   0.0    0.0  0.0   0.0   0.0          76
77       785    Venex_KI   1.0    0.0  0.0   0.0   0.0          77
78       808    Venex_KI   1.0    0.0  0.0   0.0   0.0          78
79       809    Venex_KI   1.0    0.0  0.0   0.0   0.0          79
80       799    Venex_KI   1.0    0.0  0.0   1.0   0.0          80
81       662    Venex_KI   NaN    0.0  0.0   0.0   1.0          81
82       747    Venex_KI   0.0    1.0  0.0   0.0   0.0          82
83       815    Venex_KI   1.0    0.0  0.0   0.0   0.0          83
84       660    Venex_KI   0.0    0.0  0.0   0.0   0.0          84
85       659    Venex_KI   1.0    0.0  0.0   0.0   0.0          85
86       794    Venex_KI   0.0    0.0  0.0   0.0   0.0          86

### **Anonymized mutation labels**

In [26]:
mutation_map = {
    "RTK_RAS_mutations": "A",
    "NPM1_OR_FLT3_ITD": "B",
    "CpG_mutations": "C",
    "FLT3_mutations": "D",
    "FLT3_ITD": "E",
    "NPM1": "F",
    "MDS_related_mutations": "G",
    "Transcription_mutations": "H",
    "DNMT3A": "I",
    "chromatin_cohesin_mutations": "J",
    "IDH_mutations": "K",
    "complex_karyotype": "L",
    "TET2": "M",
    "Spliceosome_mutations": "N",
    "monosomal_karyotype": "O",
    "RAS_mutations": "P",
    "IDH2": "Q",
    "trisomy_add_dup_amp_8": "R",
    "monosomy_del_7": "S",
    "TP53_OR_monosomy17_del_17p": "T",
    "monosomy5_del_5q": "U",
    "RUNX1": "V",
    "NRAS": "W",
    "SRSF2": "X",
    "TP53": "Y",
    "BCOR_mutations": "Z",
    "FLT3_TKD": "AA",
    "BCOR": "AB",
    "ASXL1": "AC",
    "RUNX1-RUNX1T1_OR_t_8_21": "AD",
    "monosomy17_del_17p": "AE",
    "WT1": "AF",
    "IDH1": "AG",
    "CEBPA": "AH",
    "PTPN11": "AI",
    "translocation11": "AJ",
    "KRAS": "AK",
    "JAK2": "AL",
    "GATA_mutations": "AM",
    "STAG2": "AN",
    "translocation3": "AO",
    "GATA2": "AP",
    "NF1": "AQ",
    "CBL": "AR",
    "PHF6": "AS",
    "U2AF1": "AT",
    "KIT": "AU",
    "KMT2A_rearrangement": "AV",
    "CBFB-MYH11": "AW",
    "EP300": "AX",
    "EZH2": "AY",
    "PML-RARA": "AZ"
}

In [27]:
mutation_labels_anonymized =  mutation_labels.copy()
for variable in existing_variables:
    mutation_labels_anonymized = mutation_labels_anonymized.rename(columns={variable: mutation_map[variable]})

display(mutation_labels_anonymized.head())

if SAVE_FILES:
    mutation_labels_anonymized.to_excel(f"data/{DATE}/sweden_bm_samples_{DATE}.xlsx", index=False)

   album_id database_id    F   AN   AU    Q    Y  subject_id
0       693    Venex_KI  0.0  0.0  0.0  1.0  0.0           0
1       763    Venex_KI  0.0  0.0  0.0  0.0  0.0           1
2       762    Venex_KI  1.0  0.0  0.0  0.0  0.0           2
3       793    Venex_KI  0.0  0.0  0.0  0.0  0.0           3
4       690    Venex_KI  0.0  0.0  0.0  0.0  0.0           4