In [1]:
import pandas as pd

In [71]:
CLINICAL_DATA_PATH_BM = "data/07-04-2026/aml_mut_pred_unprocessed_clinical_data_bm_07-04-2026.csv"
df = pd.read_csv(CLINICAL_DATA_PATH_BM)

df.filter(like="blast")

     ERY_megaloblast_mild  ERY_megaloblast   bm_blast bm_sideroblast
0                     0.0              1.0  27.500000            NaN
1                     0.0              0.0  45.000000            NaN
2                     0.0              0.0  30.000000            NaN
3                     0.0              0.0  49.333333            NaN
4                     1.0              1.0  36.000000            NaN
..                    ...              ...        ...            ...
577                   0.0              0.0  76.666667           17.5
578                   0.0              1.0  21.000000            NaN
579                   0.0              0.0  72.333333            NaN
580                   0.0              0.0  14.000000            NaN
581                   1.0              1.0  49.666667            NaN

[582 rows x 4 columns]

In [74]:
CLINICAL_DATA_PATH_BM = "data/07-04-2026/aml_mut_pred_unprocessed_clinical_data_bm_07-04-2026.csv"

fab = pd.read_csv("~/mounts/research/husdatalake/disease/processed_data/AML_morphotype/datasets/clinical_combined_V1_2.csv")
fab = fab[["henkilotunnus", "FAB"]]

print(len(fab))
print(len(fab.dropna(subset="FAB")))

df = pd.read_csv(CLINICAL_DATA_PATH_BM)
df = df[["henkilotunnus", "album_id", "year", "etiology"]]

df = df.merge(fab, how="left", on=["henkilotunnus"])
print(len(df))
#df = df.dropna(subset="FAB")
print(len(df))
df.head()

569
391
582
582

    henkilotunnus  album_id           year   etiology  FAB
0  02139_00197762       300  VisionDB_2018  secondary  NaN
1  02139_00425479       290  VisionDB_2013    de novo  NaN
2  02139_00569925       306  VisionDB_2016    de novo  NaN
3  02139_00648785       298  VisionDB_2018    de novo   M2
4  02139_00818770      1777  VisionDB_2021    de novo   M2

In [24]:
df = pd.read_parquet("~/mounts/research/husdatalake/data/pathology/qpati/textmined/pathology_text_mined.parquet")
df = df[["henkilotunnus", "fab"]]
df1 = df.dropna(subset="fab")
df1 = df1.drop_duplicates(subset="henkilotunnus")
df1

          henkilotunnus fab
1137613  02139_11422693  M4
1137726  02139_36711312  M3
1137830  02139_90114057  M3
1138149  02139_91164912  M5
1138189  02139_74864199  M5
...                 ...  ..
1372715  02139_93768454  M2
1372856  02139_39077831  M4
1373019  02139_78176059  M1
1373163  02139_56150269  M1
1373961  02139_60158583  M5

[691 rows x 2 columns]

In [25]:
CLINICAL_DATA_PATH_BM = "data/07-04-2026/aml_mut_pred_unprocessed_clinical_data_bm_07-04-2026.csv"
df = pd.read_csv(CLINICAL_DATA_PATH_BM)
df2 = df[["henkilotunnus", "album_id", "year"]]

In [26]:
df = df2.merge(df1, how="inner", on="henkilotunnus")
df.shape

(256, 4)